import { db } from '../db';
import { foods } from '../db/schema';

export const seedFoods = async () => {
  // Alimentos chilenos comunes con valores nutricionales
  const chileanFoods = [
    {
      name: 'Pan Marraqueta',
      brand: null,
      calories: 280,
      protein: 9,
      carbs: 52,
      fat: 3,
      fiber: 2.5,
      sodium: 560,
      sugar: 2,
      servingSize: 100,
      servingUnit: 'g',
      barcode: null,
      source: 'local',
      isCustom: false,
      userId: null,
    },
    {
      name: 'Palta (Aguacate)',
      brand: null,
      calories: 160,
      protein: 2,
      carbs: 9,
      fat: 15,
      fiber: 7,
      sodium: 7,
      sugar: 0.7,
      servingSize: 100,
      servingUnit: 'g',
      barcode: null,
      source: 'local',
      isCustom: false,
      userId: null,
    },
    {
      name: 'Tomate',
      brand: null,
      calories: 18,
      protein: 0.9,
      carbs: 3.9,
      fat: 0.2,
      fiber: 1.2,
      sodium: 5,
      sugar: 2.6,
      servingSize: 100,
      servingUnit: 'g',
      barcode: null,
      source: 'local',
      isCustom: false,
      userId: null,
    },
    {
      name: 'Huevo',
      brand: null,
      calories: 155,
      protein: 13,
      carbs: 1.1,
      fat: 11,
      fiber: 0,
      sodium: 124,
      sugar: 0.6,
      servingSize: 100,
      servingUnit: 'g',
      barcode: null,
      source: 'local',
      isCustom: false,
      userId: null,
    },
    {
      name: 'Queso Gouda',
      brand: null,
      calories: 380,
      protein: 24,
      carbs: 2.2,
      fat: 31,
      fiber: 0,
      sodium: 819,
      sugar: 0.5,
      servingSize: 100,
      servingUnit: 'g',
      barcode: null,
      source: 'local',
      isCustom: false,
      userId: null,
    },
    {
      name: 'Leche Entera',
      brand: 'Soprole',
      calories: 61,
      protein: 3.1,
      carbs: 4.8,
      fat: 3.3,
      fiber: 0,
      sodium: 44,
      sugar: 4.8,
      servingSize: 100,
      servingUnit: 'ml',
      barcode: null,
      source: 'local',
      isCustom: false,
      userId: null,
    },
    {
      name: 'Arroz Blanco Cocido',
      brand: null,
      calories: 130,
      protein: 2.7,
      carbs: 28,
      fat: 0.3,
      fiber: 0.4,
      sodium: 1,
      sugar: 0.1,
      servingSize: 100,
      servingUnit: 'g',
      barcode: null,
      source: 'local',
      isCustom: false,
      userId: null,
    },
    {
      name: 'Pollo a la Plancha',
      brand: null,
      calories: 239,
      protein: 27,
      carbs: 0,
      fat: 14,
      fiber: 0,
      sodium: 82,
      sugar: 0,
      servingSize: 100,
      servingUnit: 'g',
      barcode: null,
      source: 'local',
      isCustom: false,
      userId: null,
    },
    {
      name: 'Filete de Pescado',
      brand: null,
      calories: 206,
      protein: 22,
      carbs: 0,
      fat: 12,
      fiber: 0,
      sodium: 111,
      sugar: 0,
      servingSize: 100,
      servingUnit: 'g',
      barcode: null,
      source: 'local',
      isCustom: false,
      userId: null,
    },
    {
      name: 'Papas Fritas',
      brand: null,
      calories: 319,
      protein: 3.5,
      carbs: 41,
      fat: 17,
      fiber: 3.5,
      sodium: 321,
      sugar: 0.3,
      servingSize: 100,
      servingUnit: 'g',
      barcode: null,
      source: 'local',
      isCustom: false,
      userId: null,
    },
  ];

  try {
    // Check if foods already exist
    const existing = await db.select().from(foods).limit(1);
    
    if (existing.length === 0) {
      console.log('Insertando alimentos chilenos...');
      await db.insert(foods).values(chileanFoods);
      console.log(`✅ Se insertaron ${chileanFoods.length} alimentos.`);
    } else {
      console.log('✅ Los alimentos ya están en la base de datos.');
    }
  } catch (error) {
    console.error('Error al seedear alimentos:', error);
  }
};

